# Generated by Django 4.1.4 on 2022-12-12 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание товара')),
                ('category', models.CharField(choices=[('other', 'разное'), ('food', 'еда'), ('drinks', 'напитки'), ('sweets', 'сладости')], default='other', max_length=30, verbose_name='Категория товара')),
                ('amount', models.PositiveIntegerField(verbose_name='Остаток товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара')),
            ],
        ),
    ]
