# Generated by Django 4.1.4 on 2023-01-09 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('webapp', '0003_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='sessions.session'),
        ),
    ]
