# Generated by Django 4.1.4 on 2023-01-09 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_cart_user_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
