# Generated by Django 4.1.4 on 2023-01-29 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_orderproduct_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproducts', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
